### ISSUE TITLE
Errors on unity version 2018.1.0.f2

### ISSUE THREAD

**Issue by JamesTompkins** [FreyaHolmer/ShaderForge#1]
I am getting the error:
`TypeLoadException: Could not load type 'UnityEngine.ProceduralMaterial' from assembly 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
UnityEngine.ScriptableObject:CreateInstance()
ShaderForge.SF_Editor:InitializeInstance(Shader)
ShaderForge.SF_Editor:Init(Shader)
ShaderForgeMaterialInspector:OnInspectorGUI() (at Assets/ShaderForge/Editor/InternalResources/Inspectors/ShaderForgeMaterialInspector.cs:85)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

Whilst trying to open the editor

**Comment by ErikBehar** [comment]
This is due to Unity removing Substance in 2018.

If you need SF to work in 2018, here is my 2018 working branch...  https://github.com/ErikBehar/ShaderForge/tree/u2018 ... HOWEVER, there is a Unity issue that basically makes most of the shaders you make not completely work in 2018.1.0f2 : https://issuetracker.unity3d.com/issues/using-forward-add-shadow-rendering-mode-produces-irrelevant-syntax-error  

@FreyaHolmer  should we make a branch for 2018 in your repo or attempt to 
#if !UNITY_2018_OR_NEWER all the changes as I've started to do on my branch ? Or maybe someone suggest a better way to handle it  ?

**Comment by JamesTompkins** [comment]
I tried fixing myself but the errors pointed to the DLL file which I'm not versed in. What version would you suggest to downgrade to to use it?

**Comment by ErikBehar** [comment]
If you are using source code then I suggest you delete the .dll . If you want to use Shader Forge in 2018 use my branch for now, if you want to be able to compile in 2018 then you will need a version mentioned in the Issue Tracker: 2018.2.0a5 and above. I can update here if they back port the fix.

**Comment by JamesTompkins** [comment]
Thank you both for the help

**Comment by ErikBehar** [comment]
@pharan I spoke with @FreyaHolmer  on the unitydevs slack, I think the goal is to lightly maintain this repo, the suggestion was to make a 2017 and earlier branch and then maintain master on latest release. I think you may submit PR's and @FreyaHolmer  will get to them eventually.

**Comment by celeronpm** [comment]
I'm also seeing issues with LIGHT_ATTENUATION. Any fixed to use UNITY_LIGHT_ATTENUATION instead on 2018?

**Comment by ErikBehar** [comment]
@celeronpm  https://github.com/Invertex/ShaderForge/commit/9120322ccc917ce5a96e38f05ca22cce27f3d81b

**Comment by pedro15** [comment]
As i know Shaders made in unity before 2018.x will not work on SRP. the shader model changed in 2018.x
i stick with 2017.3 and i'm waiting to unity's shadergraph gets the same level of shaderforge

**Comment by pedro15** [comment]
@ErikBehar  Is not very easy to port ShaderForge to SRP. many things changed...
See is thread that i've made in the shadergraph repository:
https://github.com/Unity-Technologies/ShaderGraph/issues/364

that is only for some of the missing nodes

**Comment by ErikBehar** [comment]
@pedro15 I think the way SF mocked the Unity Standard shader with SF PBR shader is a good way of thinking about it, ie PBR SF shader != Standard shader, but it's close enough. So basically looking at the final shader result for a normal SRP shader and creating a main node that comes close directly in vert frag shader following the requirements for that SRP. I'm not a shader wiz, but I think it can be done.

**Comment by frideal** [comment]
Does ShaderForge will Update any More?

**Comment by FreyaHolmer** [comment]
I'll probably not update it anymore no. It's at least not currently planned. It might happen in the future, but don't count on it :)

**Comment by medamap** [comment]
Hello.
I forced it to work with Unity 2018 though I forced it.
May I push to GitHub?

**Comment by darkhog** [comment]
> 
> 
> I'll probably not update it anymore no. It's at least not currently planned. It might happen in the future, but don't count on it :)

How about accepting pull requests though? Wouldn't require you to actively work on it, just check once in a month or so and accept all reasonable PRs, such as those that makes it compatible with newer versions of Unity.

**Comment by xiangyuan** [comment]
unity 2018 3 f2 fresnel not work @ErikBehar

**Comment by ErikBehar** [comment]
@xiangyuan could you provide more information, is there an error log, does it only not work with that version, does it work with previous, what are the symptoms?

**Comment by xiangyuan** [comment]
> @xiangyuan could you provide more information, is there an error log, does it only not work with that version, does it work with previous, what are the symptoms?

sorry for response too late some mistake by myself, it work perfect on 2018

**Comment by FreyaHolmer** [comment]
This has now been fixed! Although it's primarily for 2019 support rather than 2018 support :) Hope it helps!
