### ISSUE TITLE
GPU Instancing On DX11&DX12

### ISSUE THREAD

**Issue by Ouyang-Zhaoxing** [FreyaHolmer/ShaderForge#10]
GPU Instancing On DX11&DX12 failed.

**Comment by Ouyang-Zhaoxing** [comment]
If you remove the following code in the shader, it will work.
**UNITY_VERTEX_INPUT_INSTANCE_ID**
**UNITY_SETUP_INSTANCE_ID( v )**
**UNITY_TRANSFER_INSTANCE_ID( v, o )**

**Comment by FreyaHolmer** [comment]
hey! I'm pretty sure removing those would break instancing entirely - do you know how to make it work on DX11/12 rather than revert back to non-instanced properties?

**Comment by Ouyang-Zhaoxing** [comment]
> hey! I'm pretty sure removing those would break instancing entirely - do you know how to make it work on DX11/12 rather than revert back to non-instanced properties?

I'm not sure, but when I deleted it worked.
In the **stats** panel of the Game window, **Batches** is normal, and **Draw Calls** in the profiler window are also normal.

I am viewing the related documents.
https://docs.unity3d.com/Manual/GPUInstancing.html

**Comment by Ouyang-Zhaoxing** [comment]
@FreyaHolmer If you can, I hope you can tell me how to fix it, of course I don't want to disturb you.

**Comment by FreyaHolmer** [comment]
This should have been fixed now in 31a58d6
