### ISSUE TITLE
Stylesheet on website not loading correctly

### ISSUE THREAD

**Issue by MattFenner** [FreyaHolmer/ShaderForge#14]
The stylesheet (css) is not loading on the website (in chrome).

This is because the page is served through through https, but the css is served through http. Chrome doesn't like this. 

I assume this is something that later versions have restricted since the website was created.

**Comment by MattFenner** [comment]
Changing this line:
![image](https://user-images.githubusercontent.com/1695492/83943404-28415e00-a83f-11ea-8c81-6c49bf22703f.png)
to this:
![image](https://user-images.githubusercontent.com/1695492/83943412-37281080-a83f-11ea-846d-4d65c8774d80.png)
fixes it.

I would be happy to submit a pull request if the website is open source?

**Comment by FreyaHolmer** [comment]
ah, thanks, it's fixed now!
