### ISSUE TITLE
Not working with 2020.2.4f1

### ISSUE THREAD

**Issue by tacosontitan** [FreyaHolmer/ShaderForge#17]
I downloaded the ZIP, extracted the files, then dropped the folder into my Assets folder, which triggered an import. I receive an error stating that the XR settings file is corrupt or serialized with a newer version of Unity.

**Comment by TheAidency** [comment]
Works for me, here's what I did: I opened the project itself separately, and exported it as a Unitypackage. That should work for most repositories, and is good practice in general. Hope it helped!!
