### ISSUE TITLE
Does not work on macbook m1

### ISSUE THREAD

**Issue by AymanDzhabari-azur** [FreyaHolmer/ShaderForge#20]
Hi!) I bought myself a macbook pro 14 (m1 pro) and ShaderForge writes - "On older GPUs/iOS it was impossible to resolve AA and at the same time preserve AA-ed surface for future usage". I am on version 2022.1.2f1, how can this be solved?

**Comment by FreyaHolmer** [comment]
where are you reading this error message? and does it contain any other info?

(also, I don't officially support Shader Forge anymore)
