### ISSUE TITLE
Windows Editor didn't opened properly in Unity 2018.3

### ISSUE THREAD

**Issue by mufabil45** [FreyaHolmer/ShaderForge#5]
Hello, I've tried it on Unity 2018.3+, Do you have any plan to update it or wait until Unity 2018.3 fully released ? ,thanks in advanced.

![2018-12-02 06_14_14-](https://user-images.githubusercontent.com/37070857/49333882-a34a0880-f5f9-11e8-9c99-aacfdb988d86.png)

Errors message when I'm opening the window

**Comment by Jennal** [comment]
Same problem here.

**Comment by southrop** [comment]
ShaderForge is discontinued and no longer supported.

**Comment by darkhog** [comment]
While that's true, people who have to rely on the legacy rendering pipeline for one reason or another (in my case it's performance - no joke, after porting my game to LWRP I had WORSE performance than I had with legacy pipeline so I have switched back) need a shader editor of some sort as shader graph doesn't support legacy pipeline.

This is the problematic code:

```
// Make sure it only renders using DrawMesh, to make ignore the scene. This is a bit risky, due to using reflection :(
			BindingFlags bfs = BindingFlags.Static | BindingFlags.NonPublic;
			Type[] args = new Type[]{ typeof(Camera) };
			mSetCameraOnlyDrawMesh = typeof( Handles ).GetMethod( "SetCameraOnlyDrawMesh", bfs, null, args, null );
			mSetCameraOnlyDrawMesh.Invoke( null, new object[]{ cam } );
```

The very last line above is the 140 line in SF_PreviewWindow.cs. It seems like it tries to reflect something in UnityEditor.Handles but comes up with a null? I'm pretty sure this is the cause of the issue, but don't have enough knowledge of editor scripting or reflection to fix it. Perhaps someone else can?

**Comment by southrop** [comment]
At no point did I tell you or anyone to migrate to the new rendering pipelines. I was just pointing out that this repository is no longer supported, and thus creating issues like this won't result in any fixes. Your easiest option is to use one of the various forks that have been updated to support 2018.3, such as [roguesleipnir/ShaderForge](https://github.com/roguesleipnir/ShaderForge).

**Comment by FreyaHolmer** [comment]
This should now be fixed! At least partially - you won't get the errors anymore, but the 3D viewport will show your scene content. It's not ideal, but, I'll hopefully fix it in the next version!
